# Generated by Django 5.1 on 2024-08-28 14:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('ip_address', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMAIL_HOST', models.CharField(blank=True, default='smtp3.danielmandelblat.com', max_length=55, null=True)),
                ('EMAIL_PORT', models.PositiveIntegerField(blank=True, default=25, null=True)),
                ('EMAIL_USE_TLS', models.BooleanField(default=False)),
                ('EMAIL_HOST_USER', models.CharField(blank=True, max_length=55, null=True)),
                ('EMAIL_HOST_PASSWORD', models.CharField(blank=True, max_length=55, null=True)),
                ('FROM_EMAIL', models.CharField(blank=True, default='auth-system@danielmandelblat.com', max_length=55, null=True)),
                ('CODE_TIMEOUT', models.PositiveIntegerField(default=30, help_text='How long the latest code is valid in minutes')),
            ],
        ),
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('code', models.UUIDField(default=uuid.uuid4)),
                ('status', models.BooleanField(blank=True, help_text='Authentication status', null=True)),
                ('ip_address', models.CharField(max_length=250)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('process_id', models.URLField(default=uuid.uuid4)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.email')),
            ],
        ),
    ]
