# Generated by Django 5.1 on 2024-08-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(auto_created=True)),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(auto_created=True)),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
