# Generated by Django 5.1 on 2024-08-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMAIL_HOST', models.CharField(blank=True, default='smtp3.danielmandelblat.com', max_length=55, null=True)),
                ('EMAIL_PORT', models.PositiveIntegerField(blank=True, default=25, null=True)),
                ('EMAIL_USE_TLS', models.BooleanField(default=False)),
                ('EMAIL_HOST_USER', models.CharField(blank=True, max_length=55, null=True)),
                ('EMAIL_HOST_PASSWORD', models.CharField(blank=True, max_length=55, null=True)),
                ('FROM_EMAIL', models.CharField(blank=True, default='authentication-service@danielmandelblat.com', max_length=55, null=True)),
            ],
        ),
    ]
