# Generated by Django 5.1 on 2024-08-27 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_sitesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='code',
        ),
        migrations.AlterField(
            model_name='email',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(auto_created=True)),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('code', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('ip_address', models.CharField(max_length=250)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.email')),
            ],
        ),
    ]
