# Generated by Django 5.1 on 2024-08-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_remove_email_code_alter_email_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
