# Generated by Django 5.1 on 2024-08-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_alter_authentication_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authentication',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
