# Generated by Django 5.1 on 2024-08-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_sitesettings_code_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='ip_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
