# Generated by Django 5.1 on 2024-08-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_log_ip_address_alter_log_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='code_timeout',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='FROM_EMAIL',
            field=models.CharField(blank=True, default='auth-system@danielmandelblat.com', max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='CODE_TIMEOUT',
            field=models.PositiveIntegerField(default=30, help_text='How long the latest code is valid in minutes'),
        ),
    ]
